permalink: /:year/:month/:day/:title.html
# 当修改文件时重新生成站点
auto: true
pygments: true
# baseurl: /coleflowers.github.com
baseurl: /
comments :
provider : disqus
disqus :
short_name : coleflowers
# 基本参数
title: 小马的Github博客
production_url: http://coleflowers.github.io
atom_path : /atom.xml
author :
  name : coleflowers
  email : coleflowers@163.com
